config/routes.rb
Rails.application.routes.draw do
  resources :tokens, only: %i[index show new create] do
    patch :trade, on: :member
  end
  resources :trades, only: %i[index show]
  devise_for :users
  root 'top#index'
end

app/models/token.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: tokens
#
#  id            :integer          not null, primary key
#  name          :string
#  symbol        :string
#  totalTokens   :decimal(, )
#  token_address :string
#  owner_id      :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  price         :integer
#

require 'ethereum'

class Token < ApplicationRecord
  has_many :trades, dependent: :destroy
  has_many :possessions, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :symbol, presence: true, uniqueness: true
  validates :totalTokens, numericality: { only_integer: true, greater_than: 0 }

  ETHEREUM_PATH = '/Users/rebit_n005/testnet/geth.ipc'
  ETHEREUM_TOKEN_PATH = "#{Dir.pwd}/contracts/ERC20Token.sol"
  ERC20TOKEN_ABI = <<-ABI
  [
    {"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},
    {"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_amount","type":"uint256"}],
    "name":"approve","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},
    {"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"totalSupply","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},
    {"constant":false,"inputs":[{"name":"_owner","type":"address"},{"name":"_to","type":"address"},{"name":"_amount","type":"uint256"}],"name":"transferInternal",
    "outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},
    {"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_amount","type":"uint256"}],"name":"transferFrom",
    "outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},
    {"constant":true,"inputs":[],"name":"floats","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},
    {"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balance","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},
    {"constant":true,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},
    {"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},
    {"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_amount","type":"uint256"}],"name":"transfer","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},
    {"constant":true,"inputs":[{"name":"_owner","type":"address"},{"name":"_spender","type":"address"}],"name":"allowance","outputs":[{"name":"remaining","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},
    {"inputs":[{"name":"_owner","type":"address"},{"name":"_name","type":"string"},{"name":"_symbol","type":"string"},{"name":"_totalTokens","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},
    {"anonymous":false,"inputs":[{"indexed":true,"name":"_from","type":"address"},{"indexed":true,"name":"_to","type":"address"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Transfer","type":"event"},
    {"anonymous":false,"inputs":[{"indexed":true,"name":"_owner","type":"address"},{"indexed":true,"name":"_spender","type":"address"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Approval","type":"event"}
  ]
  ABI

  def total_supply
    @client = Ethereum::IpcClient.new(ETHEREUM_PATH)
    user = User.first
    @client.personal_unlock_account(user.address, user.ether_password)
    contract = Ethereum::Contract.create(file: ETHEREUM_TOKEN_PATH, client: @client,
                                         address: token_address, abi: ERC20TOKEN_ABI)
    contract.call.total_supply
  end

  def balance_of(user)
    @client = Ethereum::IpcClient.new(ETHEREUM_PATH)
    # @client.personal_unlock_account(user.address, user.ether_password)
    contract = Ethereum::Contract.create(file: ETHEREUM_TOKEN_PATH, client: @client,
                                         address: token_address, abi: ERC20TOKEN_ABI)
    contract.call.balance_of(user.address)
  end

  def balance(user)
    possession = possessions.group_by(&:user_id)[user.id]
    possession.present? ? possession.first.balance : 0
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_action :set_token, only: %i[show trade]
  before_action :check_ico_client, only: %i[new create]

  def index
    @tokens = Token.all.includes(:possessions)
  end

  def show
    @trade = @token.trades.build
    @trade.trade_details.build
    @users = User.where.not(id: current_user.id)
  end

  def new
    @token = Token.new
  end

  def create
    @token = Token.new(tokens_params)
    @token.owner_id = current_user.id
    if @token.valid?
      token_address = TokenDeployService.new(current_user, @token).perform
      @token.token_address = token_address
      @possession = @token.possessions.build(user: current_user, balance: @token.totalTokens)
      if token_address.present? && @token.save && @possession.save
        redirect_to tokens_path, notice: 'Success Create Token!'
      else
        render 'new'
      end
    else
      render 'new'
    end
  end

  def trade
    @trade = @token.trades.build(trade_params)
    @trade.user = current_user
    @trade.trade_details.each { |td| td.delete if td.token_amount.blank? }
    if @trade.valid? && @trade.trade_details.present?
      ts_success_flg = TradeService.new(current_user, @trade.token, @trade).perform
      if ts_success_flg
        redirect_to trades_path, notice: 'Trade is success!'
      else
        redirect_to token_path(@token)
      end
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def set_token
    @token = Token.find(params[:id])
  end

  def tokens_params
    params.require(:token).permit(:name, :symbol, :totalTokens, :price)
  end

  def trade_params
    params.require(:trade).permit(trade_details_attributes: %i[user_id token_amount])
  end
end

app/views/tokens/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Token List</h1>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Symbol</th>
          <th>Token Name</th>
          <th>Token Possession</th>
          <th>Total Tokens</th>
          <th>Token Address</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @tokens.each do |token| %>
          <tr>
            <td><%= token.symbol %></td>
            <td><%= token.name %></td>
            <th><%= token.balance(current_user) %></th>
            <td><%= token.totalTokens %></td>
            <td><%= token.token_address %></td>
            <td><%= link_to 'Show', token_path(token), class: 'btn btn-sm btn-info' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>
  <br>
  <br>
  <% if current_user.ico_client %>
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
      <%= link_to 'Create New Token', new_token_path, class:'btn btn-primary btn-block'%>
    </div>
  <% end %>
</div>

app/views/tokens/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>New Token Set</h3>
    <%= form_for(@token) do |f|%>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <br>
      <%= f.label :symbol %>
      <%= f.text_field :symbol, class: 'form-control' %>
      <br>
      <%= f.label :TotalTokens %>
      <%= f.text_field :totalTokens, class: 'form-control' %>
      <br>
      <%= f.label :price %>
      <%= f.text_field :price, class: 'form-control' %>
      <br>
      <%= f.submit 'Create New Token', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/tokens/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h3><%= "Token: #{@token.name}" %></h3>
  <h6><%= "(address: #{@token.token_address})" %></h6>
  <h6><%= "Your ether: #{current_user.eth_balance}(ether)" %></h6>
  <%= form_for(@trade, url: trade_token_path(@token), html: { method: :patch }) do |f| %>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th class='col-xs-3'>Name</th>
            <th class='col-xs-3'>Max Token</th>
            <th class='col-xs-6'>Purchase</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
             <% next if @token.balance(user) == 0 %>
             <%= f.fields_for :trade_details do |trade_detail_f| %>
              <tr>
                <td><%= user.email %></td>
                <%= trade_detail_f.hidden_field :user_id, value: user.id %>
                <td><%= @token.balance(user) %></th>
                <td><%= trade_detail_f.text_field :token_amount %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= f.submit 'Buy Token', class: 'btn btn-success', data: { confirm: '送信しますか？' } %>
  <% end %>
</div>