config/routes.rb
Rails.application.routes.draw do
  resources :tokens, only: %i[index show new create] do
    patch :trade, on: :member
  end
  resources :trades, only: %i[index show]
  devise_for :users
  root 'top#index'
end

app/models/trade.rb
# == Schema Information
#
# Table name: trades
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  token_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Trade < ApplicationRecord
  belongs_to :user
  belongs_to :token
  has_many :trade_details, dependent: :destroy
  validate :token_amount_check
  validate :ether_check

  accepts_nested_attributes_for :trade_details

  scope :list, lambda {
    includes(:user, :token, trade_details: :user).order(created_at: :desc)
  }

  def to_user_emails
    trade_details.map { |td| td.user.email }
  end

  private

  def token_amount_check
    trade_details.each do |td|
      errors.add(:token_amount, ': トークン所持量をオーバーしています') if td.token_amount.to_i > token.balance(user)
    end
  end

  def ether_check
    trade_details.each do |td|
      eth_value = token.price.to_i * td.token_amount.to_i
      errors.add(:ether, ': Etherが不足しています') if eth_value > user.eth_balance
    end
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: %i[show]

  def index
    @trades = Trade.list.page(params[:page]).per(50)
  end

  def show
    @trade_details = @trade.trade_details.includes(:user)
  end

  private

  def set_trade
    @trade = Trade.find(params[:id])
  end
end

app/helpers/trades_helper.rb
module TradesHelper
  def not_current_users
    User.all.reject { |u| u == current_user }
  end
end

app/views/trades/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h3>Token Trade Information List</h3>
  <%= paginate(@trades) %>
  <%= page_entries_info(@trades) %>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th class='col-xs-3'>From</th>
          <th class='col-xs-3'>To</th>
          <th class='col-xs-3'>Token</th>
          <th class='col-xs-3'>Traded At</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @trades.each do |trade| %>
          <% user = trade.user %>
          <tr>
            <td><%= user.email %></td>
            <td>
              <% trade.to_user_emails.each do |email| %>
                <%= email %>
                <br>
              <% end %>
            </td>
            <td><%= trade.token.name %></td>
            <td><%= trade.created_at.try(:strftime, '%F %T') %></td>
            <td><%= link_to 'Show', trade_path(trade), class: 'btn btn-sm btn-info' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= paginate(@trades) %>
</div>

app/views/trades/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h3>Token Trade Information List</h3>
  <%= "Token: #{@trade.token.name}" %>
  <br>
  <%= "Traded At: #{@trade.created_at.try(:strftime, '%F %T')}" %>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th class='col-xs-3'>To</th>
          <th class='col-xs-3'>Ether</th>
          <th class='col-xs-3'>Token Amount</th>
        </tr>
      </thead>
      <tbody>
        <% @trade_details.each do |td| %>
          <tr>
            <td><%= td.user.email %></td>
            <td><%= td.ether %></td>
            <td><%= td.token_amount %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>