config/routes.rb
Rails.application.routes.draw do
  resources :tokens, only: %i[index show new create] do
    patch :trade, on: :member
  end
  resources :trades, only: %i[index show]
  devise_for :users
  root 'top#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EthereumTokenTrader</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Ethereum Token Trader", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to 'Token List', tokens_path %></li>
              <li><%= link_to 'Trade History', trades_path %></li>
              <li><%= link_to current_user.email, edit_user_registration_path %></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Sign In', new_user_session_path  %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <%= yield %>
  </body>
</html>